IamJuly-july.json
KiFoundation/ki-testnet-challenge pull request #11
Opened 2021-09-06 20:41 UTC by IamJuly

2021-09-07 15:58 UTC, TarekAwwad requested changes
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face: 

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR. 

The contribution content will be reviewed later.

2021-09-07 17:08 UTC, IamJuly commented
Hey Tarek! i actually don't get why my format is wrong, maybe because of wrong 'additional Comments'? i changed it. Let me please know if it's ok :)

2021-09-09 15:34 UTC, TarekAwwad commented
Please do not remove the template file.

2021-09-15 13:49 UTC, TarekAwwad approved these changes

2021-09-17 09:38 UTC, TarekAwwad approved these changes

2021-09-17 09:39 UTC, merged