Added: Northa-is1ldur_kichain.json
KiFoundation/ki-testnet-challenge pull request #25
Opened 2021-09-07 00:20 UTC by Northa

2021-09-07 16:08 UTC, TarekAwwad requested changes
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face:

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.

The contribution content will be reviewed later.

2021-09-07 18:36 UTC, Northa commented
hey @TarekAwwad 
sorry my fold. Fixed. 
Hope everything is fine now

2021-09-09 15:38 UTC, TarekAwwad commented
Please do not remove the template file <github_username>-<moniker>.json.

2021-09-17 09:40 UTC, TarekAwwad approved these changes

2021-09-17 09:40 UTC, merged