nineseo-mmguru.json
KiFoundation/ki-testnet-challenge pull request #27
Opened 2021-09-07 00:44 UTC by nineseo

{
   "moniker": "mmguru",
   "documentationURL": "https://github.com/nineseo/testnet-ki-rizon-Ibc/",
   "ibcTransferTxHashs": ["029E1E918E8D56FF06CB16805033144F7529E5D5BBC24DB2DCCCB2854812C705,6F9C3B2F01DBFCA2D03EBECCD36F62F420B750F0434D0F58152080E3BA0EE1FA,3ADC343BD446885A2E7D190622B985652054C28E2F17583F68E63DB88A2D8F59,7D190896352EC92FE5675F3668F4037C76E02CC2BAD91227DE67A4B96C8CF55B,A577E63BF2C9D6A62BDB2475724A3C86C167207260908E96AF1E96AC28EE1E8E"],
   "additionalComments": "thank you!"
}

2021-09-07 16:09 UTC, TarekAwwad requested changes
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face:

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.

The contribution content will be reviewed later.

2021-09-09 15:39 UTC, TarekAwwad commented
Please only add one contribution file.

2021-09-09 21:59 UTC, nineseo commented
> Please only add one contribution file.

Hello! I deleted the extra file.

2021-09-15 12:06 UTC, TarekAwwad approved these changes

2021-09-15 12:06 UTC, merged